package com.Jeka8833.LinkBot.kpi;

public class SavedBD {

    // CSV to Json
    // https://www.convertcsv.com/csv-to-json.htm

    public static final String data = """
            [{
                      "lesson_id": 1,
                      "day_number": 1,
                      "lesson_number": 1,
                      "lesson_week": 1,
                      "lesson_name": "Хімія матеріалів електроніки",
                      "teacher_name": "проф. Білоус Анатолій Григорович",
                      "lesson_type": "Лек",
                      "lesson_class": "129-12",
                      "time_start": "08:30:00",
                      "time_end": "10:05:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 2,
                      "day_number": 1,
                      "lesson_number": 2,
                      "lesson_week": 1,
                      "lesson_name": "Хімія матеріалів електроніки",
                      "teacher_name": "проф. Білоус Анатолій Григорович",
                      "lesson_type": "Лек",
                      "lesson_class": "134-12",
                      "time_start": "10:25:00",
                      "time_end": "12:00:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 3,
                      "day_number": 1,
                      "lesson_number": 3,
                      "lesson_week": 1,
                      "lesson_name": "Стилі в образотворчому мистецтві",
                      "teacher_name": "проф. Жукова Наталія Анатоліївна",
                      "lesson_type": "Лек",
                      "lesson_class": "341-19",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 4,
                      "day_number": 1,
                      "lesson_number": 4,
                      "lesson_week": 1,
                      "lesson_name": "Еристика",
                      "teacher_name": "проф. Препотенська Марина Петрівна",
                      "lesson_type": "Лек",
                      "lesson_class": "339-18",
                      "time_start": "14:15:00",
                      "time_end": "15:50:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 11,
                      "day_number": 3,
                      "lesson_number": 1,
                      "lesson_week": 1,
                      "lesson_name": "Теорія електронних кіл-2",
                      "teacher_name": "доц. Витязь Олег Олексійович",
                      "lesson_type": "Лек",
                      "lesson_class": "321-12",
                      "time_start": "08:30:00",
                      "time_end": "10:05:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 5,
                      "day_number": 3,
                      "lesson_number": 3,
                      "lesson_week": 1,
                      "lesson_name": "Теорія електронних кіл-2",
                      "teacher_name": "доц. Саурова Тетяна Асадовна",
                      "lesson_type": "Прак",
                      "lesson_class": "310-12",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 6,
                      "day_number": 3,
                      "lesson_number": 4,
                      "lesson_week": 1,
                      "lesson_name": "Філософські основи наукового пізнання",
                      "teacher_name": "проф. Девтеров Ілля Володимирович",
                      "lesson_type": "Прак",
                      "lesson_class": "114-12",
                      "time_start": "14:15:00",
                      "time_end": "15:50:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 7,
                      "day_number": 4,
                      "lesson_number": 1,
                      "lesson_week": 1,
                      "lesson_name": "Фізика конденсованого стану",
                      "teacher_name": "доц. Євтушенко А. І.",
                      "lesson_type": "Лек",
                      "lesson_class": "138-12",
                      "time_start": "08:30:00",
                      "time_end": "10:05:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 8,
                      "day_number": 4,
                      "lesson_number": 2,
                      "lesson_week": 1,
                      "lesson_name": "Фізика конденсованого стану",
                      "teacher_name": "доц. Євтушенко А. І.",
                      "lesson_type": "Лек",
                      "lesson_class": "138-12",
                      "time_start": "10:25:00",
                      "time_end": "12:00:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 9,
                      "day_number": 4,
                      "lesson_number": 3,
                      "lesson_week": 1,
                      "lesson_name": "Напівпровідникова електроніка",
                      "teacher_name": "проф. Борисов Олександр Васильович",
                      "lesson_type": "Лек",
                      "lesson_class": "134-12",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 10,
                      "day_number": 4,
                      "lesson_number": 4,
                      "lesson_week": 1,
                      "lesson_name": "Теорія електронних кіл-2",
                      "teacher_name": "доц. Витязь Олег Олексійович",
                      "lesson_type": "Лек",
                      "lesson_class": "321-12",
                      "time_start": "14:15:00",
                      "time_end": "15:50:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 12,
                      "day_number": 5,
                      "lesson_number": 1,
                      "lesson_week": 1,
                      "lesson_name": "Хімія матеріалів електроніки",
                      "teacher_name": "ас. Малюта С. ..",
                      "lesson_type": "Лаб",
                      "lesson_class": "312-02",
                      "time_start": "08:30:00",
                      "time_end": "10:05:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 13,
                      "day_number": 5,
                      "lesson_number": 2,
                      "lesson_week": 1,
                      "lesson_name": "Іноземна мова-2. Практичний курс іноземної мови-2",
                      "teacher_name": "вик. Гордієнко Наталія Миколаївна",
                      "lesson_type": "Прак",
                      "lesson_class": "200-12",
                      "time_start": "10:25:00",
                      "time_end": "12:00:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 14,
                      "day_number": 5,
                      "lesson_number": 3,
                      "lesson_week": 1,
                      "lesson_name": "Єдиноборства",
                      "teacher_name": "-",
                      "lesson_type": "Прак",
                      "lesson_class": "-",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 15,
                      "day_number": 5,
                      "lesson_number": 3,
                      "lesson_week": 1,
                      "lesson_name": "Складно-координаційні види спорту",
                      "teacher_name": "-",
                      "lesson_type": "Прак",
                      "lesson_class": "-",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 16,
                      "day_number": 5,
                      "lesson_number": 3,
                      "lesson_week": 1,
                      "lesson_name": "Циклічні види спорту",
                      "teacher_name": "-",
                      "lesson_type": "Прак",
                      "lesson_class": "-",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 17,
                      "day_number": 1,
                      "lesson_number": 1,
                      "lesson_week": 2,
                      "lesson_name": "Хімія матеріалів електроніки",
                      "teacher_name": "проф. Білоус Анатолій Григорович",
                      "lesson_type": "Лек",
                      "lesson_class": "129-12",
                      "time_start": "08:30:00",
                      "time_end": "10:05:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 18,
                      "day_number": 1,
                      "lesson_number": 2,
                      "lesson_week": 2,
                      "lesson_name": "Філософські основи наукового пізнання",
                      "teacher_name": "проф. Девтеров Ілля Володимирович",
                      "lesson_type": "Лек",
                      "lesson_class": "424-12",
                      "time_start": "10:25:00",
                      "time_end": "12:00:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 19,
                      "day_number": 1,
                      "lesson_number": 3,
                      "lesson_week": 2,
                      "lesson_name": "Логіка",
                      "teacher_name": "ст.вик. Піхорович Василь Дмитрович",
                      "lesson_type": "Лек",
                      "lesson_class": "306-18",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 20,
                      "day_number": 1,
                      "lesson_number": 4,
                      "lesson_week": 2,
                      "lesson_name": "Стилі в образотворчому мистецтві",
                      "teacher_name": "проф. Жукова Наталія Анатоліївна",
                      "lesson_type": "Прак",
                      "lesson_class": "114-12",
                      "time_start": "14:15:00",
                      "time_end": "15:50:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 21,
                      "day_number": 1,
                      "lesson_number": 4,
                      "lesson_week": 2,
                      "lesson_name": "Еристика",
                      "teacher_name": "доц. Колотило Мар'яна Олексіївна",
                      "lesson_type": "Прак",
                      "lesson_class": "1-205-01",
                      "time_start": "14:15:00",
                      "time_end": "15:50:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 22,
                      "day_number": 1,
                      "lesson_number": 4,
                      "lesson_week": 2,
                      "lesson_name": "Логіка",
                      "teacher_name": "ст.вик. Піхорович Василь Дмитрович",
                      "lesson_type": "Прак",
                      "lesson_class": "230-18",
                      "time_start": "14:15:00",
                      "time_end": "15:50:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 23,
                      "day_number": 2,
                      "lesson_number": 2,
                      "lesson_week": 2,
                      "lesson_name": "Фізика конденсованого стану",
                      "teacher_name": "доц. Євтушенко А. І.",
                      "lesson_type": "Прак",
                      "lesson_class": "134-12",
                      "time_start": "10:25:00",
                      "time_end": "12:00:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 24,
                      "day_number": 2,
                      "lesson_number": 3,
                      "lesson_week": 2,
                      "lesson_name": "Напівпровідникова електроніка",
                      "teacher_name": "ас. Королевич Любомир Миколайович",
                      "lesson_type": "Лаб",
                      "lesson_class": "139-12",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 25,
                      "day_number": 2,
                      "lesson_number": 4,
                      "lesson_week": 2,
                      "lesson_name": "Теорія електронних кіл-2",
                      "teacher_name": "доц. Саурова Тетяна Асадовна",
                      "lesson_type": "Лаб",
                      "lesson_class": "310-12",
                      "time_start": "14:15:00",
                      "time_end": "15:50:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 26,
                      "day_number": 3,
                      "lesson_number": 2,
                      "lesson_week": 2,
                      "lesson_name": "Фізика конденсованого стану",
                      "teacher_name": "доц. Обухова Тетяна Юріївна",
                      "lesson_type": "Лаб",
                      "lesson_class": "134-12",
                      "time_start": "10:25:00",
                      "time_end": "12:00:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 27,
                      "day_number": 3,
                      "lesson_number": 3,
                      "lesson_week": 2,
                      "lesson_name": "Напівпровідникова електроніка",
                      "teacher_name": "ас. Шевлякова Г. В.",
                      "lesson_type": "Прак",
                      "lesson_class": "129-12",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 28,
                      "day_number": 4,
                      "lesson_number": 1,
                      "lesson_week": 2,
                      "lesson_name": "Фізика конденсованого стану",
                      "teacher_name": "доц. Євтушенко А. І.",
                      "lesson_type": "Лек",
                      "lesson_class": "138-12",
                      "time_start": "08:30:00",
                      "time_end": "10:05:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 29,
                      "day_number": 4,
                      "lesson_number": 2,
                      "lesson_week": 2,
                      "lesson_name": "Напівпровідникова електроніка",
                      "teacher_name": "проф. Борисов Олександр Васильович",
                      "lesson_type": "Лек",
                      "lesson_class": "134-12",
                      "time_start": "10:25:00",
                      "time_end": "12:00:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 30,
                      "day_number": 4,
                      "lesson_number": 3,
                      "lesson_week": 2,
                      "lesson_name": "Напівпровідникова електроніка",
                      "teacher_name": "проф. Борисов Олександр Васильович",
                      "lesson_type": "Лек",
                      "lesson_class": "134-12",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 31,
                      "day_number": 4,
                      "lesson_number": 4,
                      "lesson_week": 2,
                      "lesson_name": "Теорія електронних кіл-2",
                      "teacher_name": "доц. Витязь Олег Олексійович",
                      "lesson_type": "Лек",
                      "lesson_class": "321-12",
                      "time_start": "14:15:00",
                      "time_end": "15:50:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 32,
                      "day_number": 5,
                      "lesson_number": 1,
                      "lesson_week": 2,
                      "lesson_name": "Хімія матеріалів електроніки",
                      "teacher_name": "ас. Малюта С. ..",
                      "lesson_type": "Лаб",
                      "lesson_class": "312-02",
                      "time_start": "08:30:00",
                      "time_end": "10:05:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 33,
                      "day_number": 5,
                      "lesson_number": 2,
                      "lesson_week": 2,
                      "lesson_name": "Іноземна мова-2. Практичний курс іноземної мови-2",
                      "teacher_name": "вик. Гордієнко Наталія Миколаївна",
                      "lesson_type": "Прак",
                      "lesson_class": "200-12",
                      "time_start": "10:25:00",
                      "time_end": "12:00:00",
                      "online": true,
                      "choice": false
                  }, {
                      "lesson_id": 34,
                      "day_number": 5,
                      "lesson_number": 3,
                      "lesson_week": 2,
                      "lesson_name": "Єдиноборства",
                      "teacher_name": "-",
                      "lesson_type": "Прак",
                      "lesson_class": "-",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 35,
                      "day_number": 5,
                      "lesson_number": 3,
                      "lesson_week": 2,
                      "lesson_name": "Складно-координаційні види спорту",
                      "teacher_name": "-",
                      "lesson_type": "Прак",
                      "lesson_class": "-",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": true
                  }, {
                      "lesson_id": 36,
                      "day_number": 5,
                      "lesson_number": 3,
                      "lesson_week": 2,
                      "lesson_name": "Циклічні види спорту",
                      "teacher_name": "-",
                      "lesson_type": "Прак",
                      "lesson_class": "-",
                      "time_start": "12:20:00",
                      "time_end": "13:55:00",
                      "online": true,
                      "choice": true
                  }
              ]""";
}