package com.Jeka8833.LinkBot.kpi;

public class SavedBD {

    public static final String data = """
            [
              {
                "lesson_id": 1,
                "day_number": 1,
                "lesson_number": 1,
                "lesson_week": 1,
                "lesson_name": "Психологія наукової і технічної творчості",
                "teacher_name": "доц. Плющ О. М.",
                "lesson_type": "Лек",
                "lesson_class": "114-12",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 2,
                "day_number": 1,
                "lesson_number": 1,
                "lesson_week": 1,
                "lesson_name": "Економічна психологія",
                "teacher_name": "вик. Уманец А. О.",
                "lesson_type": "Прак",
                "lesson_class": "323-12",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 3,
                "day_number": 1,
                "lesson_number": 3,
                "lesson_week": 1,
                "lesson_name": "Політична наука: конфліктологічний підхід",
                "teacher_name": "доц. Багінський А. В.",
                "lesson_type": "Лек",
                "lesson_class": "301-18",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 4,
                "day_number": 1,
                "lesson_number": 3,
                "lesson_week": 1,
                "lesson_name": "Актуальні проблеми азійських спільнот",
                "teacher_name": "ст.вик. Василець О. І.",
                "lesson_type": "Прак",
                "lesson_class": "323-12",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 5,
                "day_number": 1,
                "lesson_number": 3,
                "lesson_week": 1,
                "lesson_name": "Основи електронного урядування",
                "teacher_name": "доц. Загвойська О. В.",
                "lesson_type": "Прак",
                "lesson_class": "333-12",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 6,
                "day_number": 1,
                "lesson_number": 3,
                "lesson_week": 1,
                "lesson_name": "Розумні міста",
                "teacher_name": "проф. Чукут С. А.",
                "lesson_type": "Лек",
                "lesson_class": "339-18",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 7,
                "day_number": 2,
                "lesson_number": 1,
                "lesson_week": 1,
                "lesson_name": "Мат. ан.-3",
                "teacher_name": "доц. Задерей Н. М.",
                "lesson_type": "Лек",
                "lesson_class": "200-12",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 8,
                "day_number": 2,
                "lesson_number": 2,
                "lesson_week": 1,
                "lesson_name": "Теорія електронних кіл-1",
                "teacher_name": "доц. Витязь О. О.",
                "lesson_type": "Лек",
                "lesson_class": "321-12",
                "time_start": "10:25:00",
                "time_end": "12:00:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 9,
                "day_number": 2,
                "lesson_number": 3,
                "lesson_week": 1,
                "lesson_name": "Обч. мат.",
                "teacher_name": "доц. Татарчук Д. Д.",
                "lesson_type": "Лек",
                "lesson_class": "134-12",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 10,
                "day_number": 3,
                "lesson_number": 2,
                "lesson_week": 1,
                "lesson_name": "Мат. ан.-3",
                "teacher_name": "доц. Задерей Н. М.",
                "lesson_type": "Прак",
                "lesson_class": "333-12",
                "time_start": "10:25:00",
                "time_end": "12:00:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 11,
                "day_number": 3,
                "lesson_number": 3,
                "lesson_week": 1,
                "lesson_name": "Іноземна мова-2. Практичний курс іноземної мови-2",
                "teacher_name": "вик. Гордієнко Н. М.",
                "lesson_type": "Прак",
                "lesson_class": "433-12",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 12,
                "day_number": 3,
                "lesson_number": 4,
                "lesson_week": 1,
                "lesson_name": "Теорія електронних кіл-1",
                "teacher_name": "доц. Саурова Т. А.",
                "lesson_type": "Лаб",
                "lesson_class": "310-12",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 13,
                "day_number": 4,
                "lesson_number": 1,
                "lesson_week": 1,
                "lesson_name": "Екол. безп. інж. діял.",
                "teacher_name": "",
                "lesson_type": "Прак",
                "lesson_class": "321-12",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 14,
                "day_number": 4,
                "lesson_number": 2,
                "lesson_week": 1,
                "lesson_name": "Обч. мат.",
                "teacher_name": "доц. Татарчук Д. Д.",
                "lesson_type": "Лаб",
                "lesson_class": "129-12",
                "time_start": "10:25:00",
                "time_end": "12:00:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 15,
                "day_number": 4,
                "lesson_number": 4,
                "lesson_week": 1,
                "lesson_name": "Психологія",
                "teacher_name": "доц. Плющ О. М.",
                "lesson_type": "Лек",
                "lesson_class": "109-07",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 16,
                "day_number": 4,
                "lesson_number": 4,
                "lesson_week": 1,
                "lesson_name": "Психологія конфлікту",
                "teacher_name": "вик. Москаленко О. В.",
                "lesson_type": "Прак",
                "lesson_class": "114-12",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 17,
                "day_number": 4,
                "lesson_number": 4,
                "lesson_week": 1,
                "lesson_name": "Соціальна психологія",
                "teacher_name": "проф. Винославська О. В.",
                "lesson_type": "Лек",
                "lesson_class": "200-12",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 18,
                "day_number": 5,
                "lesson_number": 1,
                "lesson_week": 1,
                "lesson_name": "Екол. безп. інж. діял.",
                "teacher_name": "ст.вик. Овсянкіна В. О.",
                "lesson_type": "Лек",
                "lesson_class": "200-12",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 19,
                "day_number": 5,
                "lesson_number": 2,
                "lesson_week": 1,
                "lesson_name": "Статистичні методи обробки даних",
                "teacher_name": "проф. Королюк Д. В.",
                "lesson_type": "Лек",
                "lesson_class": "138-12",
                "time_start": "10:25:00",
                "time_end": "12:00:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 20,
                "day_number": 5,
                "lesson_number": 3,
                "lesson_week": 1,
                "lesson_name": "Основи квантової теорії",
                "teacher_name": "ст.вик. Лупина Б. І.",
                "lesson_type": "Лек",
                "lesson_class": "138-12",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 21,
                "day_number": 1,
                "lesson_number": 1,
                "lesson_week": 2,
                "lesson_name": "Економічна психологія",
                "teacher_name": "доц. Кононець М. О.",
                "lesson_type": "Лек",
                "lesson_class": "",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 22,
                "day_number": 1,
                "lesson_number": 2,
                "lesson_week": 2,
                "lesson_name": "Розумні міста",
                "teacher_name": "доц. Загвойська О. В.",
                "lesson_type": "Прак",
                "lesson_class": "323-12",
                "time_start": "10:25:00",
                "time_end": "12:00:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 23,
                "day_number": 1,
                "lesson_number": 3,
                "lesson_week": 2,
                "lesson_name": "Політична наука: конфліктологічний підхід",
                "teacher_name": "доц. Багінський А. В.",
                "lesson_type": "Прак",
                "lesson_class": "319-19",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 24,
                "day_number": 1,
                "lesson_number": 3,
                "lesson_week": 2,
                "lesson_name": "Актуальні проблеми азійських спільнот",
                "teacher_name": "проф. Кутуєв П. В.",
                "lesson_type": "Лек",
                "lesson_class": "301-18",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 25,
                "day_number": 1,
                "lesson_number": 3,
                "lesson_week": 2,
                "lesson_name": "Основи електронного урядування",
                "teacher_name": "проф. Чукут С. А.",
                "lesson_type": "Лек",
                "lesson_class": "200-12",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 26,
                "day_number": 1,
                "lesson_number": 4,
                "lesson_week": 2,
                "lesson_name": "Психологія наукової і технічної творчості",
                "teacher_name": "вик. Уманец А. О.",
                "lesson_type": "Прак",
                "lesson_class": "323-12",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 27,
                "day_number": 2,
                "lesson_number": 1,
                "lesson_week": 2,
                "lesson_name": "Мат. ан.-3",
                "teacher_name": "доц. Задерей Н. М.",
                "lesson_type": "Лек",
                "lesson_class": "200-12",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 28,
                "day_number": 2,
                "lesson_number": 2,
                "lesson_week": 2,
                "lesson_name": "Теорія електронних кіл-1",
                "teacher_name": "доц. Витязь О. О.",
                "lesson_type": "Лек",
                "lesson_class": "321-12",
                "time_start": "10:25:00",
                "time_end": "12:00:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 29,
                "day_number": 2,
                "lesson_number": 3,
                "lesson_week": 2,
                "lesson_name": "Обч. мат.",
                "teacher_name": "доц. Татарчук Д. Д.",
                "lesson_type": "Лек",
                "lesson_class": "134-12",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 30,
                "day_number": 3,
                "lesson_number": 1,
                "lesson_week": 2,
                "lesson_name": "Основи квантової теорії",
                "teacher_name": "ст.вик. Лупина Б. І.",
                "lesson_type": "Прак",
                "lesson_class": "07в-12",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 31,
                "day_number": 3,
                "lesson_number": 2,
                "lesson_week": 2,
                "lesson_name": "Мат. ан.-3",
                "teacher_name": "доц. Задерей Н. М.",
                "lesson_type": "Прак",
                "lesson_class": "333-12",
                "time_start": "10:25:00",
                "time_end": "12:00:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 32,
                "day_number": 3,
                "lesson_number": 3,
                "lesson_week": 2,
                "lesson_name": "Іноземна мова-2. Практичний курс іноземної мови-2",
                "teacher_name": "вик. Гордієнко Н. М.",
                "lesson_type": "Прак",
                "lesson_class": "433-12",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 33,
                "day_number": 3,
                "lesson_number": 4,
                "lesson_week": 2,
                "lesson_name": "Теорія електронних кіл-1",
                "teacher_name": "доц. Саурова Т. А.",
                "lesson_type": "Прак",
                "lesson_class": "409-12",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 34,
                "day_number": 4,
                "lesson_number": 1,
                "lesson_week": 2,
                "lesson_name": "Статистичні методи обробки даних",
                "teacher_name": "проф. Королюк Д. В.",
                "lesson_type": "Прак",
                "lesson_class": "134-12",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 35,
                "day_number": 4,
                "lesson_number": 2,
                "lesson_week": 2,
                "lesson_name": "Обч. мат.",
                "teacher_name": "доц. Татарчук Д. Д.",
                "lesson_type": "Лаб",
                "lesson_class": "129-12",
                "time_start": "10:25:00",
                "time_end": "12:00:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 36,
                "day_number": 4,
                "lesson_number": 4,
                "lesson_week": 2,
                "lesson_name": "Психологія",
                "teacher_name": "вик. Москаленко О. В.",
                "lesson_type": "Прак",
                "lesson_class": "114-12",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 37,
                "day_number": 4,
                "lesson_number": 4,
                "lesson_week": 2,
                "lesson_name": "Психологія конфлікту",
                "teacher_name": "вик. Оніпко З. С.",
                "lesson_type": "Лек",
                "lesson_class": "109-07",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 38,
                "day_number": 4,
                "lesson_number": 4,
                "lesson_week": 2,
                "lesson_name": "Соціальна психологія",
                "teacher_name": "доц. Кононець М. О.",
                "lesson_type": "Прак",
                "lesson_class": "317-12",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": true
              },
              {
                "lesson_id": 39,
                "day_number": 5,
                "lesson_number": 1,
                "lesson_week": 2,
                "lesson_name": "Теорія електронних кіл-1",
                "teacher_name": "доц. Витязь О. О.",
                "lesson_type": "Лек",
                "lesson_class": "321-12",
                "time_start": "08:30:00",
                "time_end": "10:05:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 40,
                "day_number": 5,
                "lesson_number": 2,
                "lesson_week": 2,
                "lesson_name": "Статистичні методи обробки даних",
                "teacher_name": "проф. Королюк Д. В.",
                "lesson_type": "Лек",
                "lesson_class": "138-12",
                "time_start": "10:25:00",
                "time_end": "12:00:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 41,
                "day_number": 5,
                "lesson_number": 3,
                "lesson_week": 2,
                "lesson_name": "Основи квантової теорії",
                "teacher_name": "ст.вик. Лупина Б. І.",
                "lesson_type": "Лек",
                "lesson_class": "138-12",
                "time_start": "12:20:00",
                "time_end": "13:55:00",
                "online": true,
                "choice": false
              },
              {
                "lesson_id": 42,
                "day_number": 5,
                "lesson_number": 4,
                "lesson_week": 2,
                "lesson_name": "Основи квантової теорії",
                "teacher_name": "ст.вик. Лупина Б. І.",
                "lesson_type": "Лек",
                "lesson_class": "138-12",
                "time_start": "14:15:00",
                "time_end": "15:50:00",
                "online": true,
                "choice": false
              }
            ]""";
}